#
# ctbrec-liberica Dockerfile
#
# https://github.com/jafea7/ctbrec-liberica
#

# Pull base image.
FROM bellsoft/liberica-openjdk-alpine:latest-x86_64

# Install ffmpeg
RUN apk --no-cache add ffmpeg tzdata

# Copy the rootfs layout including files
COPY rootfs/ /

# Create the volumes
VOLUME [ "/app/captures", "/app/config" ]

# Expose server non-SSL and SSL ports
EXPOSE 8080 8443

# Initialise
ENTRYPOINT ["/app/start.sh"]
