version: '2.1'
services:
# CTBRec streaming recorder
  ctbrec:
    image: "jafea7/ctbrec-liberica"
    container_name: "CTBRec-Jafea7"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${CONFIG}:/config"
      - "${MEDIA}:/app/captures"
    ports:
      - 11080:8080
      - 11443:8443
    restart: "unless-stopped"
