#
# ctbrec-liberica Dockerfile
#
# https://github.com/jafea7/ctbrec-liberica
#

# Pull base image.
FROM bellsoft/liberica-openjdk-alpine:latest-armv7l

# Install ffmpeg
RUN apk add --no-cache bash ffmpeg tzdata

# Copy the rootfs layout including files
COPY rootfs/ /
RUN chmod 777 /*.sh

# Create the volumes
VOLUME [ "/app/captures", "/app/config" ]

# Expose server non-SSL and SSL ports
EXPOSE 8080 8443

# Initialise
ENTRYPOINT ["/app/start.sh"]
