#!/usr/bin/with-contenv sh

PUID=${PUID:-911}
PGID=${PGID:-911}

[ $(getent group $PGID) ] || addgroup ctbrec -g $PGID

[ $(getent passwd ctbrec) ] && \
  addgroup ctbrec $(getent group $PGID | cut -d: -f1) || \
  adduser -D -g "" -h /app -G $PGID -H -u $PUID ctbrec

echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u ctbrec)
User gid:    $(id -g ctbrec)
-------------------------------------
"
GRP="$(getent group $PGID | cut -d: -f1)"
USR="$(getent passwd $PUID | cut -d: -f1)"

chown -R $USR:$GRP /app
chown -R $USR:$GRP /defaults
